spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_scehdular_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Admin@123
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            threadPool:
              threadCount: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: thapabasantaritu16@gmail.com
    password: '@Domnick@123'

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



